# Generated by Django 2.0.2 on 2018-03-22 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el horario de interés', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el idioma de interés (Inglés, Español etc.)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('mobilenum', models.IntegerField()),
                ('homenum', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField(help_text='Agrega una nota u comentario', max_length=2000)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospectos.Horario')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospectos.Idioma')),
            ],
        ),
    ]
