# Generated by Django 2.0.2 on 2018-03-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospecto',
            old_name='homenum',
            new_name='cel',
        ),
        migrations.RenameField(
            model_name='prospecto',
            old_name='mobilenum',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='amaterno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
