# Generated by Django 2.0.2 on 2018-03-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0002_auto_20180321_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='cel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='tel',
            field=models.IntegerField(blank=True),
        ),
    ]
