# Generated by Django 2.0.2 on 2018-03-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0003_auto_20180321_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='amaterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='cel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
