# Generated by Django 2.0.2 on 2018-03-23 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectos', '0004_auto_20180321_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectoAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Enter comment about blog here.', max_length=1000)),
                ('accion_date', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectos.Prospecto')),
            ],
            options={
                'ordering': ['accion_date'],
            },
        ),
    ]
