# Generated by Django 2.0.2 on 2018-03-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0006_acciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acciones',
            new_name='Accion',
        ),
    ]
