# Generated by Django 2.0.2 on 2018-03-23 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0007_auto_20180322_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectoaccion',
            name='tipo_accion',
            field=models.ForeignKey(help_text='Selecciona el tipo de acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospectos.Accion'),
        ),
    ]
