# Generated by Django 2.0.2 on 2018-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0009_prospecto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa los tipos de acción', max_length=100)),
                ('comentario', models.TextField(help_text='Agrega una nota u comentario', max_length=2000)),
            ],
        ),
    ]
