# Generated by Django 2.0.2 on 2018-03-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0010_razon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectoRazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Agrega una nota u comentario', max_length=2000)),
                ('accion_date', models.DateTimeField(auto_now_add=True)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospectos.Prospecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='razon',
            name='comentario',
        ),
        migrations.AddField(
            model_name='prospectorazon',
            name='tipo_accion',
            field=models.ForeignKey(help_text='Selecciona la razón por la cuál abandonó', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospectos.Razon'),
        ),
    ]
