# Generated by Django 2.0.2 on 2018-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0012_auto_20180327_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectorazon',
            old_name='tipo_accion',
            new_name='tipo_razon',
        ),
        migrations.AlterField(
            model_name='razon',
            name='name',
            field=models.CharField(help_text='Ingresa la(s) razon(es) de desinterés', max_length=100),
        ),
    ]
