# Generated by Django 2.0.2 on 2018-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0013_auto_20180328_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectorazon',
            options={'ordering': ['accion_date']},
        ),
        migrations.AlterField(
            model_name='prospectorazon',
            name='tipo_razon',
            field=models.ManyToManyField(help_text='Selecciona la razón por la cuál abandonó. Usa cmd o ctrl para seleccionar múltiples razones', to='prospectos.Razon'),
        ),
    ]
