# Generated by Django 2.0.2 on 2018-03-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0014_auto_20180328_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectorazon',
            name='tipo_razon',
        ),
        migrations.AddField(
            model_name='prospectorazon',
            name='tipo_razon',
            field=models.ForeignKey(help_text='Selecciona el tipo de razon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospectos.Razon'),
        ),
    ]
