# Generated by Django 2.0.2 on 2018-03-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0017_auto_20180328_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectorazon',
            old_name='tipo_accion',
            new_name='tipo_razon',
        ),
    ]
