# Generated by Django 2.0.2 on 2018-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(blank=True, max_length=100, null=True)),
                ('cel', models.IntegerField(blank=True, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=400)),
                ('grupo', models.ManyToManyField(help_text='Selecciona un grupo para este alumno', to='grupos.Grupo')),
            ],
        ),
    ]
