# Generated by Django 2.0.2 on 2018-03-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(help_text='Selecciona alumno para este grupo', related_name='relacion', to='grupos.Alumno'),
        ),
    ]
