# Generated by Django 2.0.2 on 2018-03-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_grupo_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='alumnos',
        ),
    ]
