# Generated by Django 2.0.2 on 2018-03-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_remove_grupo_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ManyToManyField(blank=True, help_text='Selecciona un grupo para este alumno', to='grupos.Grupo'),
        ),
    ]
