# Generated by Django 2.0.2 on 2018-03-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_auto_20180329_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ManyToManyField(blank=True, help_text='Selecciona un grupo para este alumno', related_name='trips', to='grupos.Grupo'),
        ),
    ]
