# Generated by Django 2.0.2 on 2018-04-02 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_auto_20180329_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Idioma'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ManyToManyField(blank=True, help_text='Selecciona un grupo para este alumno', to='grupos.Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
