# Generated by Django 2.0.2 on 2018-05-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_remove_alumno_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='members',
        ),
    ]
