# Generated by Django 2.0.2 on 2018-05-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_remove_grupo_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
