# Generated by Django 2.0.2 on 2018-05-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_auto_20180516_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ManyToManyField(blank=True, help_text='Selecciona un grupo para este alumno', to='grupos.Grupo'),
        ),
    ]
