# Generated by Django 2.0.2 on 2018-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0018_grupo_nombre_preinscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre_preinscritos',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
