# Generated by Django 2.0.2 on 2018-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0019_auto_20180522_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el nombre del grupo futuro', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'Inscrito'), ('p', 'Pre-inscrito')], default='p', max_length=1),
        ),
    ]
