# Generated by Django 2.0.2 on 2018-05-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0022_membership_gpreinscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
    ]
