# Generated by Django 2.0.2 on 2018-07-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0023_auto_20180522_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='nombre_preinscritos',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='gpreinscrito',
        ),
        migrations.DeleteModel(
            name='Preinscritos',
        ),
    ]
